```{r setup, include=FALSE}
library(tidyverse)
library(synExtra)
library(here)
library(powerjoin)
library(qs)
library(plotly)
library(ggbeeswarm)
library(fgsea)

synapser::synLogin()
syn <- synExtra::synDownloader(normalizePath("~/data"), .cache = TRUE)
```

```{r}
dsrip_deseq_res <- syn("syn64007138") %>%
  read_csv() %>%
  mutate(
    expression = case_when(
      is.na(padj) ~ "ns",
      padj > 0.1 ~ "ns",
      log2FoldChange > 0 ~ "up",
      log2FoldChange < 0 ~ "down",
      TRUE ~ "ns"
    ),
    signed_p = -sign(log2FoldChange_MLE) * log10(padj)
  )

dsrip_deseq_pairwise_res <- syn("syn64007139") %>%
  read_csv() %>%
  mutate(
    expression = case_when(
      is.na(padj) ~ "ns",
      padj > 0.1 ~ "ns",
      log2FoldChange > 0 ~ "up",
      log2FoldChange < 0 ~ "down",
      TRUE ~ "ns"
    )
  )

re_meta <- syn("syn64003749") %>%
  read_csv()

re_counts <- syn("syn64005287") %>%
  read_csv()
```

Check which REs could feasible be differentially expressed. FGSEA
otherwise takes too long.

```{r}
feasible_res <- re_counts %>%
  filter(transformation == "raw") %>%
  column_to_rownames("gene_id") %>% {
    rownames(.)[rowSums(. > 5) > 3]
  }

dsrip_deseq_res_w_family <- dsrip_deseq_res %>%
  power_inner_join(
    re_meta %>%
      select(md5, repFamily, repClass, repName),
    by = c("gene_id" = "md5"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )

dsrip_deseq_res_w_family %>%
  filter(contrast == "assay_dsRIP_vs_Total") %>%
  arrange(desc(log2FoldChange))
```


Are dsRIP pulled down genes enriched in certain REs?

```{r}
re_gene_sets <- bind_rows(
  re_meta %>%
    filter(md5 %in% feasible_res) %>%
    group_nest(repFamily) %>%
    filter(map_int(data, nrow) >= 10, map_int(data, nrow) < 10000) %>%
    mutate(
      gs = map(
        data, "md5"
      ) %>%
        set_names(repFamily)
    )
)

selected_des <- dsrip_deseq_res %>%
  filter(gene_id %in% feasible_res) %>%
  # drop_na(signed_neglogp) %>%
  group_nest(contrast) %>%
  mutate(
    de_p = map(
      data,
      \(x) replace_na(x, list(signed_p = 0)) %>%
        with(
          set_names(signed_p, gene_id)
        )
    ),
    de_lfc = map(
      data,
      \(x) drop_na(x, log2FoldChange) %>%
        with(
          set_names(log2FoldChange, gene_id)
        )
    )
  )

bp_param <- BiocParallel::MulticoreParam(workers = 8)
fgsea_res_raw <- selected_des %>%
  filter(contrast != "company_Bauer_vs_Azenta") %>%
  mutate(
    res_lfc = map(
      de_lfc,
      \(x) {
        message(".")
        fgseaMultilevel(
          re_gene_sets$gs,
          x,
          BPPARAM = bp_param
        )
      }
    ),
    res_p = map(
      de_p,
      \(x) {
        message(".")
        fgseaMultilevel(
          re_gene_sets$gs,
          x,
          BPPARAM = bp_param
        )
      }
    )
  )

qsave(
  fgsea_res_raw,
  here("dsrna", "rediscover_te", "dsrip_deseq_re_enrichment_raw.qs")
)

fgsea_res_long <- fgsea_res_raw %>%
  select(contrast, starts_with("res ")) %>%
  pivot_longer(starts_with("res"), names_to = "score_type", values_to = "data") %>%
  mutate(across(score_type, \(x) str_remove(x, fixed("res_")))) %>%
  unnest(data) %>%
  mutate(
    signed_p = -sign(NES) * log10(padj),
    p_cut = cut(padj, breaks = c(-Inf, 0.01, 0.05, Inf), labels = c("<0.01", "<0.05", "ns"))
  ) %>%
  mutate(
    size_leading_edge = map_int(
      leadingEdge, length
    )
  ) %>%
  select(
    score_type, contrast, pathway,
    pval, padj, p_cut, ES, NES, size_leading_edge, size,
    leadingEdge
  )
```


```{r}
synStoreMany(
  here("dsrna", "dsrip_deseq_re_enrichment_cor.csv.gz"),
  parentId = "syn63099319",
  forceVersion = FALSE
)

```


```{r}
fgsea_plot_data <- selected_des %>%
  filter(contrast != "company_Bauer_vs_Azenta") %>%
  crossing(select(re_gene_sets, repFamily, gs)) %>%
  mutate(
    data_lfc = map2(
      de_p, gs,
      \(x, y) {
        message(".")
        plotEnrichmentData(
          y,
          x
        )
      }
    )
  )

fgsea_plot_data_long <- fgsea_plot_data %>%
  transmute(
    contrast, repFamily,
    curve_data = map(
      data_lfc, "curve"
    ),
    stats_data = map(
      data_lfc,
      \(x) {
        crossing(
          x$stats,
          maxAbsStat = x$maxAbsStat,
          spreadES = x$spreadES
        )
      }
    ),
    ticks_data = map(
      data_lfc,
      \(x) {
        crossing(
          x$ticks,
          spreadES = x$spreadES
        )
      }
    ),
    pos_data = map(
      data_lfc,
      \(x) {
        as_tibble(
          x[c("posES", "negES")]
        )
      }
    )
  )

make_fgsea_plot <- \(curve, stats, ticks, pos, facet_by) {
  p <- ggplot(
    curve
  ) +
    geom_line(aes(x=rank, y=ES), color="green") +
    geom_ribbon(
      data=stats,
      mapping=aes(
        x=rank, ymin=0,
        ymax=stat/maxAbsStat*(spreadES/4)
      ),
      fill="grey"
    ) +
    geom_segment(
      data=ticks,
      mapping=aes(
        x=rank, y=-spreadES/16,
        xend=rank, yend=spreadES/16
      ),
      size=0.2
    ) +
    geom_hline(data = pos, mapping = aes(yintercept=posES), colour="red", linetype="dashed") +
    geom_hline(data = pos, mapping = aes(yintercept=negES), colour="red", linetype="dashed") +
    geom_hline(yintercept=0, colour="black") +
    theme(
        panel.background = element_blank(),
        panel.grid.major=element_line(color="grey92")
    ) +
    labs(x="rank", y="enrichment score")
  browser()
  if (!missing(facet_by)) {
    p <- p + facet_wrap(vars({{facet_by}}))
  }
  p
}

fgsea_plot_data_long_by_contrast <- fgsea_plot_data_long %>%
  group_by(contrast) %>%
  summarize(
    across(
      ends_with("_data"),
      \(d) {
        # browser()
        bind_rows(set_names(d, repFamily), .id = "repFamily") %>%
          list()
      }
    )
  )

x <- with(
  fgsea_plot_data_long_by_contrast[1, ],
  make_fgsea_plot(
    curve_data[[1]],
    stats_data[[1]],
    ticks_data[[1]],
    pos_data[[1]],
    repFamily
  )
)
```



```{r}
# dsrip_re_cor_wide <- dsrip_re_cor_long %>%
#   select(-c(method, alternative, statistic)) %>%
#   pivot_wider(
#     names_from = contrast,
#     values_from = -c(contrast, class_family)
#   )

cor_contrast_comp_plot_data <- tribble(
  ~contrast1, ~contrast2,
  "Ctrl_RIP_vs_Total", "populationC9.assayRIP",
  "Ctrl_RIP_vs_Total", "C9_RIP_vs_Total"
) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      select(-statistic, -method, -alternative),
    by = c("contrast1" = "contrast"),
    check = check_specs(
      unmatched_keys_left = "warn"
    )
  ) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      select(-statistic, -method, -alternative),
    by = c("contrast2" = "contrast", "class_family"),
    suffix = c("_1", "_2"),
    check = check_specs(
      unmatched_keys_left = "warn"
    )
  )

cor_contrast_plot_fun <- \(data, metric, contrast1, contrast2, ...) {
  metric_ <- c(
    "estimate" = "Correlation coefficient",
    "signed_p" = "Signed -log10(padj)"
  )[metric]
  ggplot(
    data,
    aes(
      x = !!sym(paste0(metric, "_1")),
      y = !!sym(paste0(metric, "_2")),
      text = paste(
        "class_family: ", class_family
      )
    )
  ) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(alpha = .5, shape = 16) +
  coord_equal() +
  labs(
    x = paste(metric_, contrast1),
    y = paste(metric_, contrast2)
  )
}

cor_contrast_comp_plots <- cor_contrast_comp_plot_data %>%
  group_nest(contrast1, contrast2) %>%
  crossing(metric = c("estimate", "signed_p")) %>%
  mutate(
    p = pmap(
      cur_data(),
      cor_contrast_plot_fun
    )
  )

pwalk(
  cor_contrast_comp_plots,
  \(p, contrast1, contrast2, metric, ...) {
    ggsave(
      here("dsrna", "plots", paste0("dsrip_re_enrichment_cor_", contrast1, "_vs_", contrast2, "_", metric, ".pdf")),
      p,
      width = 5,
      height = 5
    )
    pp <- ggplotly(p)
    htmltools::save_html(
      pp,
      here("dsrna", "plots", paste0("dsrip_re_enrichment_cor_", contrast1, "_vs_", contrast2, "_", metric, ".html"))
    )
  }
)
```


```{r}
p <- dsrip_re_cor_data %>%
  filter(
    class_family == "LINE/L1",
    contrast == "assay_RIP_vs_Total"
  ) %>%
  ggplot(
    aes(
      x = log2FoldChange,
      y = n,
      color = expression
    )
  ) +
  geom_point(alpha = 0.5)

p <- dsrip_re_cor_data %>%
  filter(
    class_family == "LINE/L1",
    contrast == "assay_RIP_vs_Total"
  ) %>%
  ggplot(
    aes(
      x = rank(log2FoldChange),
      y = density,
      color = expression
    )
  ) +
  geom_point(alpha = 0.5)

```

```{r}
ps <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_nest(
    contrast
  ) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      group_nest(contrast, .key = "cor_data"),
    by = "contrast",
    check = check_specs(
      unmatched_keys_left = "warn", unmatched_keys_right = "warn",
      duplicate_keys_left = "warn", duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    p = map2(
      data, cor_data,
      \(x, y) ggplot(
        mutate(
          x,
          across(
            c(log2FoldChange, log2FoldChange_MLE),
            list(
              quantiles = \(x) Hmisc::cut2(x, g = 10, digits = 2)
            )
          )
        ) %>%
          filter(log2FoldChange_quantiles %in% levels(log2FoldChange_quantiles)[c(1, 10)]),
        aes(
          x = log2FoldChange_quantiles,
          y = log_density
        )
      ) +
      geom_hline(
        aes(yintercept = log10(density_floor)),
        data = \(x) distinct(x, class_family, density_floor),
        linetype = "dashed"
      ) +
      ggrastr::rasterize(geom_quasirandom(
        aes(color = expression),
        shape = 16
      ), dpi = 300) +
      geom_boxplot(
        color = "gray",
        fill = NA,
        outliers = FALSE
      ) +
      geom_text(
        aes(
          label = paste(signif(estimate, 2), signif(padj, 2))
        ),
        data = y,
        x = -Inf,
        y = Inf,
        hjust = 0,
        vjust = 1,
        inherit.aes = FALSE
      ) +
      geom_segment(
        aes(
          x = stage(log2FoldChange_quantiles, x - 0.5), xend = stage(log2FoldChange_quantiles, after_scale = xend + 0.5),
          y = log_density_mean, yend = log_density_mean
        ),
        data = \(x) x %>%
          group_by(class_family, log2FoldChange_quantiles) %>%
          summarize(log_density_mean = mean(log_density), .groups = "drop"),
        color = "gray",
        linetype = "dotted"
      ) +
      scale_color_manual(
        values = c(
          "ns" = alpha("black", .1),
          "down" = alpha("blue", .5),
          "up" = alpha("red", .5)
        )
      ) +
      ggh4x::facet_wrap2(~class_family, scales = "free", axes = "all") +
      coord_cartesian(clip = "off") +
      theme(axis.text.x = element_blank()) +
      labs(
        x = "log2FoldChange deciles",
        y = "Repeat density (per bp)"
      )
    )
  )

pwalk(
  ps,
  \(p, contrast, ...) {
    message(contrast)
    ggsave(
      here("dsrna", "plots", paste0("dsrip_re_enrichment_quantiles_top_bottom_", str_replace(contrast, "[^\\w]+", "_"), ".pdf")),
      p +
        labs(title = contrast),
      width = 12,
      height = 10
    )
  }
)
```


```{r}
ps <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_nest(
    contrast
  ) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      group_nest(contrast, .key = "cor_data"),
    by = "contrast",
    check = check_specs(
      unmatched_keys_left = "warn", unmatched_keys_right = "warn",
      duplicate_keys_left = "warn", duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    p = map2(
      data, cor_data,
      \(x, y) ggplot(
        mutate(
          x,
          across(
            c(log2FoldChange, log2FoldChange_MLE),
            list(
              quantiles = \(x) Hmisc::cut2(x, g = 10, digits = 2)
            )
          )
        ) %>%
          filter(log2FoldChange_quantiles %in% levels(log2FoldChange_quantiles)[c(1, 10)]),
        aes(
          x = log2FoldChange_quantiles,
          y = log_density
        )
      ) +
      geom_hline(
        aes(yintercept = log10(density_floor)),
        data = \(x) distinct(x, class_family, density_floor),
        linetype = "dashed"
      ) +
      ggrastr::rasterize(geom_quasirandom(
        aes(color = expression),
        shape = 16
      ), dpi = 300) +
      geom_boxplot(
        color = "gray",
        fill = NA,
        outliers = FALSE
      ) +
      geom_text(
        aes(
          label = paste(signif(estimate, 2), signif(padj, 2))
        ),
        data = y,
        x = -Inf,
        y = Inf,
        hjust = 0,
        vjust = 1,
        inherit.aes = FALSE
      ) +
      geom_segment(
        aes(
          x = stage(log2FoldChange_quantiles, x - 0.5), xend = stage(log2FoldChange_quantiles, after_scale = xend + 0.5),
          y = log_density_mean, yend = log_density_mean
        ),
        data = \(x) x %>%
          group_by(class_family, log2FoldChange_quantiles) %>%
          summarize(log_density_mean = mean(log_density), .groups = "drop"),
        color = "gray",
        linetype = "dotted"
      ) +
      scale_color_manual(
        values = c(
          "ns" = alpha("black", .1),
          "down" = alpha("blue", .5),
          "up" = alpha("red", .5)
        )
      ) +
      ggh4x::facet_wrap2(~class_family, scales = "free", axes = "all") +
      coord_cartesian(clip = "off") +
      theme(axis.text.x = element_blank()) +
      labs(
        x = "log2FoldChange deciles",
        y = "Repeat density (per bp)"
      )
    )
  )

pwalk(
  ps,
  \(p, contrast, ...) {
    message(contrast)
    ggsave(
      here("dsrna", "plots", paste0("dsrip_re_enrichment_quantiles_top_bottom_", str_replace(contrast, "[^\\w]+", "_"), ".pdf")),
      p +
        labs(title = contrast),
      width = 12,
      height = 10
    )
  }
)
```



```{r}
ps <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_nest(
    contrast
  ) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      group_nest(contrast, .key = "cor_data"),
    by = "contrast",
    check = check_specs(
      unmatched_keys_left = "warn", unmatched_keys_right = "warn",
      duplicate_keys_left = "warn", duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    p = map2(
      data, cor_data,
      \(x, y) ggplot(
        mutate(
          x,
          across(
            c(log2FoldChange, log2FoldChange_MLE),
            list(
              quantiles = \(x) Hmisc::cut2(x, g = 10, digits = 2)
            )
          ) %>%
          filter()
        ),
        aes(
          x = log2FoldChange_quantiles,
          y = log_density
        )
      ) +
      geom_hline(
        aes(yintercept = log10(density_floor)),
        data = \(x) distinct(x, class_family, density_floor),
        linetype = "dashed"
      ) +
      ggrastr::rasterize(geom_quasirandom(
        aes(color = expression),
        shape = 16
      ), dpi = 300) +
      geom_boxplot(
        color = "gray",
        fill = NA,
        outliers = FALSE
      ) +
      geom_text(
        aes(
          label = paste(signif(estimate, 2), signif(padj, 2))
        ),
        data = y,
        x = -Inf,
        y = Inf,
        hjust = 0,
        vjust = 1,
        inherit.aes = FALSE
      ) +
      geom_segment(
        aes(
          x = stage(log2FoldChange_quantiles, x - 0.5), xend = stage(log2FoldChange_quantiles, after_scale = xend + 0.5),
          y = log_density_mean, yend = log_density_mean
        ),
        data = \(x) x %>%
          group_by(class_family, log2FoldChange_quantiles) %>%
          summarize(log_density_mean = mean(log_density), .groups = "drop"),
        color = "gray",
        linetype = "dotted"
      ) +
      scale_color_manual(
        values = c(
          "ns" = alpha("black", .1),
          "down" = alpha("blue", .5),
          "up" = alpha("red", .5)
        )
      ) +
      ggh4x::facet_wrap2(~class_family, scales = "free", axes = "all") +
      theme(axis.text.x = element_blank()) +
      labs(
        x = "log2FoldChange deciles",
        y = "Repeat density (per bp)"
      )
    )
  )

pwalk(
  ps,
  \(p, contrast, ...) {
    message(contrast)
    ggsave(
      here("dsrna", "plots", paste0("dsrip_re_enrichment_quantiles_", str_replace(contrast, "[^\\w]+", "_"), ".pdf")),
      p +
        labs(title = contrast),
      width = 18,
      height = 12
    )
  }
)
```


```{r}
ps <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_nest(
    contrast
  ) %>%
  power_inner_join(
    dsrip_re_cor_long %>%
      group_nest(contrast, .key = "cor_data"),
    by = "contrast",
    check = check_specs(
      unmatched_keys_left = "warn", unmatched_keys_right = "warn",
      duplicate_keys_left = "warn", duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    p = map2(
      data, cor_data,
      \(x, y) {
        lfc_range <- quantile(x$log2FoldChange, probs = c(.05, .95))
        d <- mutate(
          x,
          across(
            c(log2FoldChange, log2FoldChange_MLE, density),
            list(
              quantiles = \(x) Hmisc::cut2(x, g = 10, digits = 2)
            )
          ),
          log2FoldChange_censored = case_when(
            log2FoldChange < lfc_range[1] ~ lfc_range[1],
            log2FoldChange > lfc_range[2] ~ lfc_range[2],
            TRUE ~ log2FoldChange
          ),
          log2FoldChange_symbol = case_when(
            log2FoldChange < lfc_range[1] ~ "<",
            log2FoldChange > lfc_range[2] ~ ">",
            TRUE ~ "="
          )
        )

      ggplot(
        d,
        aes(
          x = density_quantiles,
          y = log2FoldChange_censored
        )
      ) +
      # geom_hline(
      #   aes(yintercept = log10(density_floor)),
      #   data = \(x) distinct(x, class_family, density_floor),
      #   linetype = "dashed"
      # ) +
      ggrastr::rasterize(geom_quasirandom(
        aes(color = expression, shape = log2FoldChange_symbol)
      ), dpi = 300) +
      geom_boxplot(
        color = "gray",
        fill = NA,
        outliers = FALSE
      ) +
      geom_text(
        aes(
          label = paste(signif(estimate, 2), signif(padj, 2))
        ),
        data = y,
        x = -Inf,
        y = Inf,
        hjust = 0,
        vjust = 1,
        inherit.aes = FALSE
      ) +
      # geom_segment(
      #   aes(
      #     x = stage(log2FoldChange_quantiles, x - 0.5), xend = stage(log2FoldChange_quantiles, after_scale = xend + 0.5),
      #     y = log_density_mean, yend = log_density_mean
      #   ),
      #   data = \(x) x %>%
      #     group_by(class_family, log2FoldChange_quantiles) %>%
      #     summarize(log_density_mean = mean(log_density), .groups = "drop"),
      #   color = "gray",
      #   linetype = "dotted"
      # ) +
      scale_color_manual(
        values = c(
          "ns" = alpha("black", .1),
          "down" = alpha("blue", .5),
          "up" = alpha("red", .5)
        )
      ) +
      scale_shape_manual(
        values = c(
          ">" = 2,
          "<" = 6,
          "=" = 16
        )
      ) +
      ggh4x::facet_wrap2(~class_family, scales = "free", axes = "all") +
      theme(axis.text.x = element_blank()) +
      labs(
        x = "Repeats per bp deciles",
        y = "log2FoldChange"
      )
    })
  )

pwalk(
  ps,
  \(p, contrast, ...) {
    message(contrast)
    ggsave(
      here("dsrna", "plots", paste0("dsrip_re_enrichment_density_quantiles_", str_replace(contrast, "[^\\w]+", "_"), ".pdf")),
      p +
        labs(title = contrast),
      width = 18,
      height = 12
    )
  }
)
```


```{r}
p <- dsrip_re_cor_data %>%
  filter(
    class_family == "LINE/L1",
    contrast == "assay_RIP_vs_Total"
  ) %>%
  ggplot(
    aes(
      x = log2FoldChange,
      y = n,
      color = expression
    )
  ) +
  geom_point(alpha = 0.5)

p <- dsrip_re_cor_data %>%
  filter(
    class_family == "LINE/L1",
    contrast == "assay_RIP_vs_Total"
  ) %>%
  ggplot(
    aes(
      x = rank(log2FoldChange),
      y = density,
      color = expression
    )
  ) +
  geom_point(alpha = 0.5)

```


```{r}
dsrip_re_rank_data <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_by(contrast, class_family) %>%
  mutate(
    across(
      c(log2FoldChange, log2FoldChange_MLE, density),
      list(rank = rank)
    )
  ) %>%
  ungroup()


p <- dsrip_re_rank_data %>%
  filter(
    class_family == "LINE/L1",
    contrast == "Ctrl_RIP_vs_Total"
  ) %>%
  ggplot(
    aes(log2FoldChange_rank, density_rank, color = expression)
  ) +
  geom_point(alpha = 0.5)
```


```{r}
library(ggbeeswarm)
ps <- dsrip_re_cor_data %>%
  mutate(expression = factor(expression, levels = c("ns", "down", "up"))) %>%
  arrange(expression) %>%
  group_nest(class_family, keep = TRUE) %>%
  mutate(
    p = map2(
      data, class_family,
      \(d, rc) ggplot(
        d,
        aes(
          x = log2FoldChange_quantiles,
          y = log_density
        )
      ) +
      geom_hline(
        aes(yintercept = log10(density_floor)),
        data = \(x) distinct(x, class_family, density_floor),
        linetype = "dashed"
      ) +
      ggrastr::rasterize(geom_quasirandom(
        aes(color = expression),
        shape = 16
      ), dpi = 300) +
      geom_boxplot(
        color = "gray",
        fill = NA,
        outliers = FALSE,
        coef = 0
      ) +
      geom_text(
        aes(
          label = paste(signif(estimate, 2), signif(padj, 2))
        ),
        data = \(x) filter(dsrip_re_cor_long, class_family == rc),
        x = -Inf,
        y = Inf,
        hjust = 0,
        vjust = 1,
        inherit.aes = FALSE
      ) +
      geom_segment(
        aes(
          x = stage(log2FoldChange_quantiles, x - 0.5), xend = stage(log2FoldChange_quantiles, after_scale = xend + 0.5),
          y = log_density_mean, yend = log_density_mean
        ),
        data = \(x) x %>%
          group_by(class_family, log2FoldChange_quantiles) %>%
          summarize(log_density_mean = mean(log_density), .groups = "drop"),
        color = "gray",
        linetype = "dotted"
      ) +
      scale_color_manual(
        values = c(
          "ns" = alpha("black", .1),
          "down" = alpha("blue", .5),
          "up" = alpha("red", .5)
        )
      ) +
      theme(axis.text.x = element_blank()) +
      labs(
        x = "log2FoldChange deciles",
        y = "log10 repeat density (per bp)"
      )
    )
  )

dir.create(here("dsrna", "plots", "dsrip_re_enrichment_plots"), showWarnings = FALSE)
pwalk(
  ps,
  function(p, class_family, ...) {
    message(class_family)
    # browser()
    ggsave(
      here("dsrna", "plots", "dsrip_re_enrichment_plots", paste0("dsrip_re_enrichment_quantiles_", str_replace(class_family, "[^\\w]+", "_"), ".pdf")),
      p +
        labs(title = class_family),
      width = 4.5,
      height = 3.5
    )
  }
)
```
